config/routes.rb
Rails.application.routes.draw do
  
  namespace :api do
    resources :jobs
    resources :applications
  end
  
  resources :applications

  get 'password_resets/new'

  get 'password_resets/edit'

  put 'jobs/:id/status', to: 'jobs#status', as: 'status'

  root 'static_pages#home'
  
  resources :jobs do
    resources :locations
  end

  resources :users, except: :destroy

  get '/login', to: 'sessions#new'
  
  post '/login', to: 'sessions#create'
  
  delete '/logout', to: 'sessions#destroy'

  get '/dashboard', to: 'dashboards#index'

  get '/worklists', to: 'worklists#index'

  get '/allocations', to: 'worklists#allocations'

  resources :account_activations, only: [:edit]

  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/models/job.rb
class Job < ActiveRecord::Base
belongs_to :department
has_many :access_jobs
has_many :users, through: :access_jobs
belongs_to :contract
belongs_to :work_pattern
belongs_to :grade
belongs_to :status
has_many :locations

validates :title, presence: true
validates :salaryMin, presence: true, length: {maximum: 6}
validates :salaryMax, presence: true, length: {maximum: 6}
validates :jobDescription, presence: true
validates :personalSpec, presence: true
validates :grade_id, presence: true
validates :contract_id, presence: true
validates :work_pattern_id, presence: true
validates :selectDetails, presence: true

scope :allocation, -> { where(status_id: 2) }

end

app/controllers/api/jobs_controller.rb
module Api
	class JobsController < ApplicationController

		def index
			jobs = Job.all
			if status_id = params[:status_id]
				jobs = jobs.where(status_id: status_id)
			end
			respond_to do |format|
				format.json {render json: jobs, status: 200}
				format.xml {render xml: jobs, status: 200}
			end
		end

		def show
			job = Job.find(params[:id])
			render json: job, status: 200
			
		end

		def create
			job = Job.new(job_params)
			if job.save
				respond_to do |format|
					format.json {render json: job, status: 201, location: job}
					format.xml {render xml: job, status: 201, location: job}
				end
			end
		end

		private
		
		def job_params
			params.require(:job).permit(:title, :grade_id, :grade_equivalent, :jobDescription, :personalSpec, :selectDetails, :work_pattern_id, :contract_id, :status_id, :salaryMin, :salaryMax)
		end
	end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
		include SessionsHelper
		before_action :logged_in_user

	def index
		@job = current_user.jobs
	end

	def show
		@job = Job.find(params[:id])
	end

	def status
		@job = Job.find(params[:id])
		@job.update_attributes(status_id: 2)
		redirect_to jobs_path
		flash[:success] = "Your job has been sent for approval."
	end

	def new
		@job = Job.new
	end

	def create	
		@job = Job.create(job_params)
		@user = current_user.access_jobs.create(job: @job)
		if @job.save
			redirect_to new_job_location_path(@job)
		else
			render 'new'
		end
	end

	def edit 
		@job = Job.find(params[:id])
	end

	def update
		@job = Job.find(params[:id])
		if @job.update_attributes(job_params)
		redirect_to new_job_location_path(@job)
		else
			render 'edit'
		end
	end

	private

	def job_params
	params.require(:job).permit(:title, :grade_id, :grade_equivalent, :jobDescription, :personalSpec, :selectDetails, :work_pattern_id, :contract_id, :status_id, :salaryMin, :salaryMax)
	end

	def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/edit.html.erb
<h1><small>Step 1 of 3</small><br>Update your job</h1>
<%= render 'shared/job_advert' %>

app/views/jobs/index.html.erb
<h1><%= @job.count %> active <%= "job".pluralize(@job.count) %></h1>
<%= link_to "<span class='glyphicon glyphicon-plus' aria-hidden='true'></span> Add a job".html_safe, {controller: "jobs", action: "new"}, method: "get", class: "btn btn-primary" %>
<br><br>
<% @job.order("created_at desc").each do |j| %>
<div class="well well-lg">
<h3><%= j.title %></h3>
<p>Created at: <%= j.created_at.strftime("%d/%m/%Y") %></p>
<p>Ref: <%= j.id %></p>
<p>Status: <%= j.status.name %></p>
<%= link_to "Edit job advert", edit_job_path(j.id), class: "btn btn-default" %>
</div>
<% end %>

app/views/jobs/new.html.erb
<h1><small>Step 1 of 3</small><br>Create your job</h1>
<%= render 'shared/job_advert' %>

app/views/jobs/show.html.erb
<h1><small>Step 3 of 3</small><br>Preview job</h1>
<% if @job.status_id != 2 %>
<div class="jumbotron">
<%= link_to "Submit for approval", status_path(@job), method: :put, class: "btn btn-primary btn-lg" %>
&nbsp;&nbsp;<%= link_to "Return later", jobs_path %> &nbsp;&nbsp;<%= link_to "Return to step 2", new_job_location_path(@job) %>
</div>
<% else %>
<%= link_to "Return to jobs", jobs_path, class: "btn btn-primary" %><br>
<% end %>

<% content_for :content do %>
<div id="page-container">

	<div class="phase-banner">
	  <p>
	    <strong class="phase-tag">ALPHA</strong>
	    <span>This is a new service – your <a href="mailto:support.csjobs@csresourcing.gsi.gov.uk">feedback</a> will help us to improve it.</span>
	  </p>
	</div>

	<div class="row">
	<div class="col-md-4"></div>
	<div class="col-md-8">
	<h1><%= @job.title %></h1>
	</div>
		<div class="col-md-4">

			<div class="details">
				<p>Salary: <%= number_to_currency(@job.salaryMin, precision: 0, unit: "£") %> - <%= number_to_currency(@job.salaryMax, precision: 0, unit: "£") %></p>
				<p>Contract: <%= @job.contract.contract %></p>
				<p>Working pattern: <%= @job.work_pattern.working_pattern %></p>
				<p>Grade: <%= @job.grade.grade %></p>
				<% if @job.grade_equivalent? %>
				<p>Grade equivalent: <%= @job.grade_equivalent %></p>
				<% end %>
			</div>
			</div>
			<div class="col-md-8">

			<h2>Job description</h2>
			<p><%= @job.jobDescription %></p>
			<h2>Personal specification</h2>
			<p><%= @job.personalSpec %></p>
			<h2>Selection process</h2>
			<p><%= @job.selectDetails %></p>
		</div>

	</div>

</div>
<% end %>
<br>
<%= render file: 'layouts/govuk_template' %>