config/routes.rb
Rails.application.routes.draw do
  
  namespace :api do
    resources :jobs
    resources :applications
  end
  
  resources :applications

  get 'password_resets/new'

  get 'password_resets/edit'

  put 'jobs/:id/status', to: 'jobs#status', as: 'status'

  root 'static_pages#home'
  
  resources :jobs do
    resources :locations
  end

  resources :users, except: :destroy

  get '/login', to: 'sessions#new'
  
  post '/login', to: 'sessions#create'
  
  delete '/logout', to: 'sessions#destroy'

  get '/dashboard', to: 'dashboards#index'

  get '/worklists', to: 'worklists#index'

  get '/allocations', to: 'worklists#allocations'

  resources :account_activations, only: [:edit]

  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/models/access_job.rb
class AccessJob < ActiveRecord::Base
	belongs_to :job
	belongs_to :user
end

app/models/application.rb
class Application < ActiveRecord::Base
	belongs_to :job

	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :job_id, presence: true

end

app/models/contract.rb
class Contract < ActiveRecord::Base
	has_many :jobs
end

app/models/department.rb
class Department < ActiveRecord::Base
	has_many :jobs
	has_many :users
end

app/models/grade.rb
class Grade < ActiveRecord::Base
	has_many :jobs
end

app/models/job.rb
class Job < ActiveRecord::Base
belongs_to :department
has_many :access_jobs
has_many :users, through: :access_jobs
belongs_to :contract
belongs_to :work_pattern
belongs_to :grade
belongs_to :status
has_many :locations

validates :title, presence: true
validates :salaryMin, presence: true, length: {maximum: 6}
validates :salaryMax, presence: true, length: {maximum: 6}
validates :jobDescription, presence: true
validates :personalSpec, presence: true
validates :grade_id, presence: true
validates :contract_id, presence: true
validates :work_pattern_id, presence: true
validates :selectDetails, presence: true

scope :allocation, -> { where(status_id: 2) }

end

app/models/location.rb
class Location < ActiveRecord::Base
	belongs_to :job
	geocoded_by :address   # can also be an IP address
	before_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }         # auto-fetch coordinates
	validates :address, presence: true
	validates :longitude, presence: true
	validates :latitude, presence: true
end

app/models/status.rb
class Status < ActiveRecord::Base
	has_many :jobs
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :activation_token, :reset_token
	before_save :downcase_email
	before_create :create_activation_digest
	belongs_to :department
	has_many :access_jobs
	has_many :jobs, through: :access_jobs
	before_save { email.downcase! }
	validates :firstname, presence: true, length: { maximum: 50 }
	validates :lastname, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, confirmation: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	validates :department_id, presence: true
	has_secure_password
	validates :password, length: { minimum: 6 }

	# Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Activates an account.
  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

	# Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

	# Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

	private
	#sets email to lowercase
	def downcase_email
		self.email = email.downcase
	end

	# Creates and assigns the activation token and digest.
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/models/work_pattern.rb
class WorkPattern < ActiveRecord::Base
	has_many :jobs
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
		include SessionsHelper
		before_action :logged_in_user

	def index
		@job = current_user.jobs
	end

	def show
		@job = Job.find(params[:id])
	end

	def status
		@job = Job.find(params[:id])
		@job.update_attributes(status_id: 2)
		redirect_to jobs_path
		flash[:success] = "Your job has been sent for approval."
	end

	def new
		@job = Job.new
	end

	def create	
		@job = Job.create(job_params)
		@user = current_user.access_jobs.create(job: @job)
		if @job.save
			redirect_to new_job_location_path(@job)
		else
			render 'new'
		end
	end

	def edit 
		@job = Job.find(params[:id])
	end

	def update
		@job = Job.find(params[:id])
		if @job.update_attributes(job_params)
		redirect_to new_job_location_path(@job)
		else
			render 'edit'
		end
	end

	private

	def job_params
	params.require(:job).permit(:title, :grade_id, :grade_equivalent, :jobDescription, :personalSpec, :selectDetails, :work_pattern_id, :contract_id, :status_id, :salaryMin, :salaryMax)
	end

	def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	
	# Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) 
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

   # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/worklists_helper.rb
module WorklistsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EasyRecruit</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= favicon_link_tag %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Easy Recruit", root_path, class:"navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      	<% if logged_in? %>
        <li><%= link_to "Dashboard", dashboard_path %></a></li>
        <li><%= link_to "Jobs", jobs_path %></li>
        <li><%= link_to "Worklists", worklists_path %></li>
        <% end %>
      </ul>

      <ul class="nav navbar-nav navbar-right">
      	<% if logged_in? %>
      		<p class="navbar-text"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>
  <span class="sr-only">Signed in as</span> <%= current_user.firstname %> <%= current_user.lastname %></p> 
      	<% end %>
        <% if logged_in? %>
			<li role="presentation"><%= link_to "Log out", logout_path, method: "delete" %></li>
		<% else %>
			<li role="presentation"><%= link_to "Sign in", login_path %></li>
		<% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
	<div class="container">
	<div class="row">
  		<div class="col-md-12">
				<% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
  <span class="sr-only">Alert:</span> <%= message %></div>
      <% end %>
		</div>
	</div>
	<main>
		<div class="row white">
	    <div class="col-md-12">
	     	<%= yield %>
   		 </div>
   		</div>
   	</div>
   </main>
   <footer>
   </footer>
</body>
</html>

 	

app/views/shared/_account_form.html.erb
<%= render 'shared/error_messages' %>
</div>
<div class="col-md-4">
	<%= form_for @user do |f| %>
<div class="form-group">
<%= f.label :firstname, "First name" %>
<%= f.text_field :firstname, class: "form-control" %>
</div>
<div class="form-group">
<%= f.label :lastname, "Last name"%>
<%= f.text_field :lastname, class: "form-control"  %>
</div>
<div class="form-group">
<%= f.label :email, "Work email" %>
<%= f.email_field :email, class: "form-control"  %>
</div>
<div class="form-group">
<%= f.label :email_confirmation, "Confirm work email" %>
<%= f.email_field :email_confirmation, class: "form-control"  %>
</div>
<div class="form-group">
<%= f.label :department_id %>
<%= f.select :department_id, Department.all.collect { |d| [ d.name, d.id ] }, {include_blank: true}, class: "form-control" %>
</div>
<div class="form-group">
<%= f.label :password, "Password" %>
<%= f.text_field :password, class: "form-control", type: "password" %>
</div>
<div class="form-group">
<%= f.label :password_confirmation, "Confirm password" %>
<%= f.text_field :password_confirmation, class: "form-control", type: "password" %>
</div>
<div class="form-group">
<%= f.submit class: "btn btn-primary"  %>
</div>
<% end %>
</div>

app/views/shared/_application_error.html.erb
<% if @application.errors.any? %>
<div class="alert alert-danger" role="alert">
		<p><span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
  <span class="sr-only">Error:</span>The form contains <%= pluralize(@application.errors.count, "error") %>.
	<ul>
		<% @application.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>

app/views/shared/_application_form.html.erb
<div class="col-md-6">
<%= render 'shared/application_error' %>
<%= form_for @application do |f| %>
<div class="form-group">
<%= f.label :first_name, "first name" %>
<%= f.text_field :first_name, class: 'form-control' %>
</div>
<div class="form-group">
<%= f.label :last_name, "Last name" %>
<%= f.text_field :last_name, class: 'form-control' %>
</div>
<div class="form-group">
<%= f.label :email, "Email" %>
<%= f.text_field :email, class: 'form-control' %>
</div>
<div class="form-group">
<%= f.label :job_id, "Job ID" %>
<%= f.number_field :job_id, class: 'form-control' %>
</div>
<div class="form-group">
<%= f.submit "Save and continue", class: "btn btn-primary" %>
</div>
<% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
<div class="alert alert-danger" role="alert">
		<p><span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
  <span class="sr-only">Error:</span>The form contains <%= pluralize(@user.errors.count, "error") %>.
	<ul>
		<% @user.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>

app/views/shared/_job_advert.html.erb
<%= render 'shared/job_error' %>
<div class="col-md-6">
<%= form_for @job do |f| %>
<div class="form-group">
<%= f.label :title %>
<%= f.text_field :title, class: 'form-control' %>
</div>
<div class="form-group">
<%= f.label :salaryMin, "Minimum salary" %>
<div class="input-group">
<span class="input-group-addon">£</span>
<%= f.number_field :salaryMin, class: 'form-control' %>
</div>
</div>
<div class="form-group">
<%= f.label :salaryMax, "Maximum salary" %>
<div class="input-group">
<span class="input-group-addon">£</span>
<%= f.number_field :salaryMax, class: 'form-control' %>
</div>
</div>
<div class="form-group">
<%= f.label :grade_id, "Grade"%>
<%= f.select :grade_id, Grade.all.collect { |g| [ g.grade, g.id ] }, {include_blank: true}, class: "form-control" %>
</div>
<div class="form-group">
<%= f.label :grade_equivalent, "Equivalent grade (optional)" %>
<%= f.text_field :grade_equivalent, class: 'form-control' %>
</div>
<div class="form-group">
<%= f.label :jobDescription, "Job description" %>
<%= f.text_area :jobDescription, rows: "9", class: 'form-control' %>
</div>
<div class="form-group">
<%= f.label :personalSpec, "Personal specification" %>
<%= f.text_area :personalSpec, rows: "9", class: 'form-control' %>
</div>
<div class="form-group">
<%= f.label :selectDetails, "Selection process" %>
<%= f.text_area :selectDetails, rows: "6", class: 'form-control' %>
</div>
<div class="form-group">
<%= f.label :contract_id, "Contract type" %>
<%= f.select :contract_id, Contract.all.collect { |d| [ d.contract, d.id ] }, {include_blank: true}, class: "form-control"  %>
</div>
<div class="form-group">
<%= f.label :work_pattern_id, "Working pattern" %>
<%= f.select :work_pattern_id, WorkPattern.all.collect { |d| [ d.working_pattern, d.id ] }, {include_blank: true}, class: "form-control"  %>
</div>
<div class="form-group">
<%= f.submit "Save and continue", class: "btn btn-primary" %>
</div>
<% end %>
</div>

app/views/shared/_job_error.html.erb
<% if @job.errors.any? %>
<div class="alert alert-danger" role="alert">
		<p><span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
  <span class="sr-only">Error:</span>The form contains <%= pluralize(@job.errors.count, "error") %>.
	<ul>
		<% @job.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>

app/views/shared/_location_form.html.erb
<div class="col-md-6">
<%= form_for ([@job, @job.locations.build])do |f| %>
<div class="form-group">
	<%= f.label :address %>
	<%= f.text_field :address, class: 'form-control' %>
</div>
<div class="form-group">
<%= f.submit "Add location", class: "btn btn-default" %>
</div>
<% end %>
<div class="form-group">
<%= link_to "Save and preview", job_path(@job), class: "btn btn-primary" %> &nbsp;&nbsp;<%= link_to "Return to step 1", edit_job_path(@job.id)%>
</div>
</div>